workflows:
  ios-release:
    name: iOS Publication
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
        - pattern: ios-stable
          include: true
        - pattern: android-stable
          include: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Update CocoaPods
        script: |
          echo "Installing latest CocoaPods..."
          sudo gem install cocoapods
          pod --version
      - name: Deep Clean
        script: |
          echo "Cleaning Flutter project..."
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ~/Library/Developer/Xcode/DerivedData
          echo "Clean complete!"
      - name: Get Flutter packages
        script: flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod repo update
          pod install --verbose
          cd ..
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: |
          echo "Building IPA in RELEASE mode..."
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
          echo "Build complete!"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
