workflows:
  ios-release:
    name: iOS Publication
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
        - pattern: ios-stable
          include: true
        - pattern: android-stable
          include: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        FLUTTER_BUILD_MODE: release
    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.posekw.gallery
    scripts:
      - name: Update CocoaPods
        script: sudo gem install cocoapods
      - name: Deep Clean
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/.symlinks
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Get Flutter packages
        script: flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
